application: ymxlive
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /static
  static_dir: static

- url: /.*
  script: engine.app
  

libraries:
- name: setuptools
  version: latest
  
- name: markupsafe
  version: latest
  
- name: jinja2
  version: latest
  